"""empty message

Revision ID: 4a7b122c1a21
Revises: ff225d20b87e
Create Date: 2022-05-30 11:36:29.083693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7b122c1a21'
down_revision = 'ff225d20b87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show','start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('Show', sa.Column('start_time',sa.DateTime(timezone=False),
               nullable=False)
              )

    # ### end Alembic commands ###
