"""empty message

Revision ID: c454510a787b
Revises: 31f7cefa64b5
Create Date: 2022-05-30 22:17:19.645269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c454510a787b'
down_revision = '31f7cefa64b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue','image_link',existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('Artist','image_link',existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue','image_link',existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('Artist','image_link',existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
