"""empty message

Revision ID: dbaadcb9ec29
Revises: ed5fd1726c2c
Create Date: 2022-05-26 16:07:39.512486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbaadcb9ec29'
down_revision = 'ed5fd1726c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist','website_link',new_column_name="website")
    op.alter_column('Venue', 'website_link',new_column_name="website")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist','website',new_column_name="website_link")
    op.alter_column('Venue', 'website',new_column_name="website_link")
    # ### end Alembic commands ###
